### ISSUE TITLE
version.py causes crash 

### ISSUE THREAD

**Issue by nejsan** [ponty/confduino#1]
`version.py` has been causing crashes for me on an Ubuntu 14.04 VM.  The error I'm getting is:
```
ValueError: invalid literal for int() with base 10: '1:1'
```

This seems to be because it's parsing the components of the version string "1:1.0.5+dfsg2-2" into integers, when the parts contain non-numeric characters. I created a hotfix for it by importing `re` and changing a line in `intversion()` to the following:
```
s = s.split('ubuntu')[0]
s = re.search('(\d+\.)+\d', s).group()
```

This fixed it for my specific case, but I don't know if that will cause problems on different systems. I also don't like resorting to a regex here.

**Comment by ponty** [comment]
This was already fixed in 8f8306ea359ba2782cb29bb7a7bfa38ff78fff58
I should update it on  PYPI.
Thanks for the report!
