### ISSUE TITLE
Does this version use Arvdude for uploading

### ISSUE THREAD

**Issue by Pimmetje** [ponty/confduino#2]
Does this version use arvdude?

Would it be doable to have the uploading native in python?

Like : https://github.com/christophediericx/ArduinoSketchUploader made in .Net?

**Comment by ponty** [comment]
Upload is not implemented in current version.
It may be supported in the future through Arduino command line interface.
Native Python implementation is not planned at all.
This library is only for wrapping Arduino environment, nothing will be reimplemented.

**Comment by Pimmetje** [comment]
Thanks for the replay
